### ISSUE TITLE
Možnosti

### ISSUE THREAD

**Issue by Denisko696** [SneznyKocur/wocabot#4]
Čauko, mohol by si mi prosím vysvetliť čo robia všetky, ospravedlňujem sa ak to niekde je, ale nikde som to nedokázal nájsť   
--practice
  --points TARGET_POINTS
  --class CLASSID
  --package PACKAGE
  --do-package
  --learn-all
  --get-classes, --classes
  --get-packages, --packages
  --get-leaderboard, --leaderboard
  --auto
  --leaderboard-pos, --pos
  --learn

**Comment by SneznyKocur** [comment]
--practice: precvičovanie balíkov (len na body)
--points (body): počet bodov na získanie (buď len počet bodov koľko chceš aby si mal alebo potom +(x bodov) aby prirátalo x bodov k tvojmu počtu)
--class (id): špecifikuje akú triedu (potrebné na skoro všetky príkazy)
--package: špecifikuje balík
--do-package: (urobí balík)
--learn-all: naučí sa všetky slovíčka (toto spusti predtým ako budeš robiť balíky aby vedelo preklady)
--get-classes / --classes: vypíše tvoje triedy a ich ID
--get-packages / --packaged: vypíše balíky v triede a ich ID
--get-leaderboard / --leaderboard: vypíše tabuľku bodov
--auto: urobí všetky balíky ktoré nemáš hotové
--leaderboard-pos / --pos (pos): dostane ťa na pozíciu v tabuľke (teda ak chceš byť prvý daj tu jedna a ono bude precvičovať balíky na body)
--learn: naučí sa slovíčka z konkretného balíka (treba špecifikovať balík)

ak niečo nebude fungovať prosím otvor issue lebo ja wocabee už od júla nemám tak som toto veľmi neopravoval a kto vie čo zmenili

**Comment by SneznyKocur** [comment]
môžeš aj vyskúšať [stránku](https://wocabee.sneznykocur.lol/#/) ktorú mám na toto
